version: '2'

services:
  mongo:
    image: mongo
    restart: always

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mongo
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    restart: always
    environment:
      - COUCHDB_SERVER='http://couchdb:5984/',
      - COUCHDB_DATABASE='hackatum'
    volumes:
      - './code:/code'
